#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
from answer import *

if __name__ == "__main__":
    article = str(sys.argv[1])
    questions = str(sys.argv[2])

    f = open(article, "r", encoding='utf8').read()

    ans = Answer(f)

    q = open(questions, "r", encoding='utf8')

    answers = []

    for line in q:
        answers.append(ans.answer_question(line))

    for ind in answers:
        print(ind)
